version: 2.1

jobs:
  run-unit-tests:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Install PyTest
          command: pip install PyTest
      - run:
          name: Run PyTest
          command: |
            python -m pytest tests/ --junitxml=pytest.xml

      - store_test_results:
          path: pytest.xml

  generate-code-coverage:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Install PyTest
          command: pip install PyTest
      - run:
          name: Install Coverage
          command: pip install coverage
      - run:
          name: Coverage run
          command: coverage run -m pytest tests/ || true
      - run:
          name: Coverage report
          command: coverage report

      - run:
          name: Coverage HTML
          command: coverage html

      # anybadge
      - run:
          name: Generate Coverage Badge
          command: |
            coverage report | grep '/^TOTAL.+?(\d+\%)$/'
            

      - store_artifacts:
          path: htmlcov

workflows:
  run-tests-and-coverage:
    jobs:
      - run-unit-tests
      - generate-code-coverage

